"""message

Revision ID: 1c15311208b4
Revises: aefa7eb36707
Create Date: 2024-07-15 22:33:04.448792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c15311208b4'
down_revision = 'aefa7eb36707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
